matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io -w /io $DOCKER_IMAGE /io/travis/build-wheels.sh
  - ls dist/
